version: '2'
services:
  ldap:
    image: osixia/openldap:1.2.2
    restart: always
    env_file:
      - ldap.env
    environment:
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config
    volumes:
      - ldap:/var/lib/ldap
      - slapd.d:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 639:639

  app:
    build: .
    restart: always
    volumes:
      - ${PWD}/app:/easyldap/app:ro
    ports:
      - 5000:5000
    depends_on:
      - ldap

volumes:
  ldap:
  slapd.d:
